# Generated by Django 4.0.1 on 2023-01-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='img_read',
            field=models.TextField(),
        ),
    ]
